name: Persist Labels
on:
  label:
    types:
      - created
      - edited
      - deleted

jobs:
  persist-labels:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: org_repos

      - uses: EndBug/export-label-config@v1
        with:
          raw-result: false
          add-aliases: false

      - uses: actions/download-artifact@v3
        with:
          name: 'Label config'
          path: ./artifacts

      - name: LS
        run: ls -R
  
      - name: Sync labels to all repos
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: ./artifacts/labels.yaml
          repository: ${{ steps.org_repos.outputs.repositories }}
          token: ${{ secrets.GITHUB_TOKEN }}
